POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS code rest client is a pretty handy tool",
  "important": true
}
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "User id of the note creator is at the start sent along the request",
  "important": true,
  "userId": "689fc1891ef44aada4554489"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "I wonder how Spring Boot works",
  "important": false,
  "userId": "689fc1891ef44aada4554489"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODlmYzE4OTFlZjQ0YWFkYTQ1NTQ0ODkiLCJpYXQiOjE3NTU0MTM5NjB9.IwrfJ3NSnrGEogI2vazzDkeMKVMgIhj74cgdeCHrGi4

{
  "content": "Single page apps use token based auth",
  "important": false
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODlmYzE4OTFlZjQ0YWFkYTQ1NTQ0ODkiLCJpYXQiOjE3NTU1MzU4NzYsImV4cCI6MTc1NTUzNTkzNn0.qMuyXl5tYfYq7644d0DaXBBndkQI-viFDBwc3NnwDRU

{
  "content": "Trying to make a new note after the token has expired",
  "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODlmYzE4OTFlZjQ0YWFkYTQ1NTQ0ODkiLCJpYXQiOjE3NTU1MzYwMDAsImV4cCI6MTc1NTUzNjA2MH0.X8xZcTfV7kcgKsQD8gkxDqMv6r9_XBu2hyeH3eU4k9w

{
  "content": "Hello world",
  "important": false
}